# Generated by Django 4.2.30 on 2026-06-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criancas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('impressa', models.BooleanField(default=False)),
                ('data_impressao', models.DateTimeField(blank=True, null=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criancas.crianca')),
                ('presenca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta', to='presencas.presencadiaria')),
                ('usuario_geracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
