# Generated by Django 4.2.30 on 2026-06-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('token_qr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('autorizacao_imagem', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
    ]
