# Generated by Django 4.2.30 on 2026-06-05 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsaveis', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('alergias', models.TextField(blank=True)),
                ('restricoes_alimentares', models.TextField(blank=True)),
                ('cuidados_especiais', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('autorizacao_imagem', models.BooleanField(default=False)),
                ('token_qr', models.CharField(db_index=True, max_length=100, unique=True)),
                ('codigo_interno', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criancas', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='CriancaResponsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parentesco', models.CharField(default='Responsável', max_length=50)),
                ('pode_fazer_checkin', models.BooleanField(default=True)),
                ('pode_fazer_checkout', models.BooleanField(default=True)),
                ('pode_editar_dados', models.BooleanField(default=False)),
                ('responsavel_principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crianca_responsavel', to='criancas.crianca')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crianca_responsavel', to='responsaveis.responsavel')),
            ],
            options={
                'verbose_name': 'Criança-Responsável',
                'verbose_name_plural': 'Criança-Responsáveis',
                'unique_together': {('crianca', 'responsavel')},
            },
        ),
    ]
