# Generated by Django 4.2.30 on 2026-06-05 17:38

import criancas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criancas', '0004_alter_crianca_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='foto',
            field=models.ImageField(null=True, upload_to=criancas.models.caminho_foto_crianca),
        ),
    ]
