# Generated by Django 4.2.30 on 2026-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('responsavel', 'Responsável'), ('recepcao', 'Recepção'), ('checkin', 'Check-in'), ('professor', 'Professor'), ('checkout', 'Checkout'), ('coordenacao', 'Coordenação'), ('admin', 'Admin')], default='responsavel', max_length=20),
        ),
    ]
