# Generated by Django 4.2.30 on 2026-06-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsaveis', '0001_initial'),
        ('criancas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('NAO_CHEGOU', 'Não chegou'), ('PRESENTE', 'Presente'), ('RETIRADA', 'Retirada'), ('AUSENTE', 'Ausente')], default='NAO_CHEGOU', max_length=20)),
                ('horario_checkin', models.DateTimeField(blank=True, null=True)),
                ('horario_checkout', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='criancas.crianca')),
                ('responsavel_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_checkin', to='responsaveis.responsavel')),
                ('responsavel_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_checkout', to='responsaveis.responsavel')),
                ('usuario_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_checkin', to=settings.AUTH_USER_MODEL)),
                ('usuario_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_checkout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presença Diária',
                'verbose_name_plural': 'Presenças Diárias',
                'ordering': ['-data', 'crianca__nome_completo'],
                'unique_together': {('crianca', 'data')},
            },
        ),
    ]
