# Generated by Django 4.2.30 on 2026-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencadiaria',
            name='checkout_token',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='presencadiaria',
            name='checkout_token_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
