# Generated by Django 4.2.30 on 2026-06-05 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('criancas', '0005_alter_crianca_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsaveis', '0002_alter_responsavel_autorizacao_imagem'),
        ('presencas', '0002_presencadiaria_checkout_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeOperacaoLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=80, unique=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes_lote_criados', to=settings.AUTH_USER_MODEL)),
                ('criancas', models.ManyToManyField(related_name='qrcodes_lote', to='criancas.crianca')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes_lote', to='responsaveis.responsavel')),
            ],
            options={
                'verbose_name': 'QR Code de Operação em Lote',
                'verbose_name_plural': 'QR Codes de Operação em Lote',
                'ordering': ['-criado_em'],
            },
        ),
    ]
